### ISSUE TITLE
Error on Home Assistant RC 2023.12.0b0

### ISSUE THREAD

**Issue by eduardoribeiro** [peribeir/pyrademacher#54]
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 00:10:15 (1 occurrences)
Last logged: 00:10:15

Setup failed for custom integration 'rademacher': Requirements for rademacher not found: ['pyrademacher==0.13.1'].

**Comment by eduardoribeiro** [comment]
I've updated the integration to the latest version which should include also pyrademacher 0.13.1

**Comment by eduardoribeiro** [comment]
There's another error being reported:
Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 22:25:58 (3 occurrences)
Last logged: 22:26:08

Unable to install package pyrademacher==0.13.1: ERROR: Cannot install pyrademacher==0.13.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by peribeir** [comment]
PR #55 will solve the issue.
v0.13.2 released, Integration to follow.
